import "dotenv/config";
import { fileCreateTool } from "../../tools/file/create";

async function main() {
	console.log("🚀 Starting file.create test...");

	const testArgs = {
		path: "test-output/hello-world.txt",
		// 実際には外部から注入されるが、直接叩くので内容を記述
		content: `Test content generated by script.\nDate: ${new Date().toISOString()}`,
	};

	console.log(`📝 Target path: ${testArgs.path}`);

	// handler を直接実行
	const response = await fileCreateTool.handler(testArgs);

	// 'status' ではなく 'success' プロパティを確認
	if (response.success) {
		console.log("✅ SUCCESS:");
		// 成功時は response.summary にメッセージが入っている
		console.log(`Summary: ${response.summary}`);
	} else {
		console.error("❌ FAILED:");
		// 失敗時は response.error に詳細が入っている
		console.error(`Error: ${response.error}`);
	}
}

main().catch((err) => {
	console.error("💥 Critical script error:", err);
	process.exit(1);
});
